Using cache found in C:\Users\Andrea/.cache\torch\hub\pytorch_vision_v0.10.0
Traceback (most recent call last):
  File "c:\Users\Andrea\Desktop\VisionAndPerceptionProject\trainer.py", line 144, in <module>
    trainer.train()
  File "c:\Users\Andrea\Desktop\VisionAndPerceptionProject\trainer.py", line 45, in train
    output=self.model(patches)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\googlenet.py", line 172, in forward
    x, aux1, aux2 = self._forward(x)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\googlenet.py", line 110, in _forward
    x = self.conv1(x)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\googlenet.py", line 271, in forward
    x = self.conv(x)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [320, 3]